album:
    path:     /
    defaults: { _controller: "SportClubBundle:Album:index" }

album_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:Album:show" }

album_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:Album:new" }

album_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:Album:create" }
    methods:  POST

album_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:Album:edit" }

album_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:Album:update" }
    methods:  [POST, PUT]

album_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:Album:delete" }
    methods:  [POST, DELETE]
