artist:
    path:     /
    defaults: { _controller: "SportClubBundle:Artist:index" }

artist_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:Artist:show" }

artist_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:Artist:new" }

artist_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:Artist:create" }
    methods:  POST

artist_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:Artist:edit" }

artist_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:Artist:update" }
    methods:  [POST, PUT]

artist_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:Artist:delete" }
    methods:  [POST, DELETE]
