audiocategory:
    path:     /
    defaults: { _controller: "SportClubBundle:AudioCategory:index" }

audiocategory_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:AudioCategory:show" }

audiocategory_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:AudioCategory:new" }

audiocategory_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:AudioCategory:create" }
    methods:  POST

audiocategory_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:AudioCategory:edit" }

audiocategory_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:AudioCategory:update" }
    methods:  [POST, PUT]

audiocategory_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:AudioCategory:delete" }
    methods:  [POST, DELETE]
