audiotype:
    path:     /
    defaults: { _controller: "SportClubBundle:AudioType:index" }

audiotype_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:AudioType:show" }

audiotype_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:AudioType:new" }

audiotype_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:AudioType:create" }
    methods:  POST

audiotype_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:AudioType:edit" }

audiotype_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:AudioType:update" }
    methods:  [POST, PUT]

audiotype_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:AudioType:delete" }
    methods:  [POST, DELETE]
