bannertype:
    path:     /
    defaults: { _controller: "SportClubBundle:BannerType:index" }

bannertype_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:BannerType:show" }

bannertype_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:BannerType:new" }

bannertype_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:BannerType:create" }
    methods:  POST

bannertype_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:BannerType:edit" }

bannertype_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:BannerType:update" }
    methods:  [POST, PUT]

bannertype_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:BannerType:delete" }
    methods:  [POST, DELETE]
