bannerposition:
    path:     /
    defaults: { _controller: "SportClubBundle:BannerPosition:index" }

bannerposition_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:BannerPosition:show" }

bannerposition_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:BannerPosition:new" }

bannerposition_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:BannerPosition:create" }
    methods:  POST

bannerposition_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:BannerPosition:edit" }

bannerposition_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:BannerPosition:update" }
    methods:  [POST, PUT]

bannerposition_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:BannerPosition:delete" }
    methods:  [POST, DELETE]
