click:
    path:     /
    defaults: { _controller: "SportClubBundle:Click:index" }

click_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:Click:show" }

click_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:Click:new" }

click_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:Click:create" }
    methods:  POST

click_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:Click:edit" }

click_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:Click:update" }
    methods:  [POST, PUT]

click_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:Click:delete" }
    methods:  [POST, DELETE]
