day:
    path:     /
    defaults: { _controller: "SportClubBundle:Day:index" }

day_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:Day:show" }

day_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:Day:new" }

day_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:Day:create" }
    methods:  POST

day_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:Day:edit" }

day_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:Day:update" }
    methods:  [POST, PUT]

day_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:Day:delete" }
    methods:  [POST, DELETE]
