faq:
    path:     /
    defaults: { _controller: "SportClubBundle:Faq:index" }

faq_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:Faq:show" }

faq_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:Faq:new" }

faq_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:Faq:create" }
    methods:  POST

faq_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:Faq:edit" }

faq_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:Faq:update" }
    methods:  [POST, PUT]

faq_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:Faq:delete" }
    methods:  [POST, DELETE]
