gallery:
    path:     /
    defaults: { _controller: "SportClubBundle:Gallery:index" }

gallery_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:Gallery:show" }

gallery_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:Gallery:new" }

gallery_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:Gallery:create" }
    methods:  POST

gallery_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:Gallery:edit" }

gallery_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:Gallery:update" }
    methods:  [POST, PUT]

gallery_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:Gallery:delete" }
    methods:  [POST, DELETE]
