imagecategory:
    path:     /
    defaults: { _controller: "SportClubBundle:ImageCategory:index" }

imagecategory_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:ImageCategory:show" }

imagecategory_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:ImageCategory:new" }

imagecategory_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:ImageCategory:create" }
    methods:  POST

imagecategory_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:ImageCategory:edit" }

imagecategory_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:ImageCategory:update" }
    methods:  [POST, PUT]

imagecategory_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:ImageCategory:delete" }
    methods:  [POST, DELETE]
