language:
    path:     /
    defaults: { _controller: "SportClubBundle:Language:index" }

language_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:Language:show" }

language_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:Language:new" }

language_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:Language:create" }
    methods:  POST

language_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:Language:edit" }

language_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:Language:update" }
    methods:  [POST, PUT]

language_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:Language:delete" }
    methods:  [POST, DELETE]
