livechannel:
    path:     /
    defaults: { _controller: "SportClubBundle:LiveChannel:index" }

livechannel_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:LiveChannel:show" }

livechannel_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:LiveChannel:new" }

livechannel_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:LiveChannel:create" }
    methods:  POST

livechannel_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:LiveChannel:edit" }

livechannel_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:LiveChannel:update" }
    methods:  [POST, PUT]

livechannel_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:LiveChannel:delete" }
    methods:  [POST, DELETE]
