matchgoal:
    path:     /
    defaults: { _controller: "SportClubBundle:MatchGoal:index" }

matchgoal_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:MatchGoal:show" }

matchgoal_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:MatchGoal:new" }

matchgoal_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:MatchGoal:create" }
    methods:  POST

matchgoal_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:MatchGoal:edit" }

matchgoal_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:MatchGoal:update" }
    methods:  [POST, PUT]

matchgoal_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:MatchGoal:delete" }
    methods:  [POST, DELETE]
