matchcommentary:
    path:     /
    defaults: { _controller: "SportClubBundle:MatchCommentary:index" }

matchcommentary_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:MatchCommentary:show" }

matchcommentary_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:MatchCommentary:new" }

matchcommentary_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:MatchCommentary:create" }
    methods:  POST

matchcommentary_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:MatchCommentary:edit" }

matchcommentary_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:MatchCommentary:update" }
    methods:  [POST, PUT]

matchcommentary_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:MatchCommentary:delete" }
    methods:  [POST, DELETE]
