matchcard:
    path:     /
    defaults: { _controller: "SportClubBundle:MatchCard:index" }

matchcard_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:MatchCard:show" }

matchcard_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:MatchCard:new" }

matchcard_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:MatchCard:create" }
    methods:  POST

matchcard_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:MatchCard:edit" }

matchcard_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:MatchCard:update" }
    methods:  [POST, PUT]

matchcard_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:MatchCard:delete" }
    methods:  [POST, DELETE]
