matchlineup:
    path:     /
    defaults: { _controller: "SportClubBundle:MatchLineUp:index" }

matchlineup_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:MatchLineUp:show" }

matchlineup_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:MatchLineUp:new" }

matchlineup_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:MatchLineUp:create" }
    methods:  POST

matchlineup_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:MatchLineUp:edit" }

matchlineup_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:MatchLineUp:update" }
    methods:  [POST, PUT]

matchlineup_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:MatchLineUp:delete" }
    methods:  [POST, DELETE]
