matchsubstitution:
    path:     /
    defaults: { _controller: "SportClubBundle:MatchSubstitution:index" }

matchsubstitution_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:MatchSubstitution:show" }

matchsubstitution_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:MatchSubstitution:new" }

matchsubstitution_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:MatchSubstitution:create" }
    methods:  POST

matchsubstitution_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:MatchSubstitution:edit" }

matchsubstitution_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:MatchSubstitution:update" }
    methods:  [POST, PUT]

matchsubstitution_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:MatchSubstitution:delete" }
    methods:  [POST, DELETE]
