match:
    path:     /
    defaults: { _controller: "SportClubBundle:Match:index" }

match_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:Match:show" }

match_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:Match:new" }

match_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:Match:create" }
    methods:  POST

match_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:Match:edit" }

match_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:Match:update" }
    methods:  [POST, PUT]

match_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:Match:delete" }
    methods:  [POST, DELETE]
