menu:
    path:     /
    defaults: { _controller: "SportClubBundle:Menu:index" }

menu_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:Menu:show" }

menu_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:Menu:new" }

menu_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:Menu:create" }
    methods:  POST

menu_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:Menu:edit" }

menu_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:Menu:update" }
    methods:  [POST, PUT]

menu_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:Menu:delete" }
    methods:  [POST, DELETE]
