packagetype:
    path:     /
    defaults: { _controller: "SportClubBundle:PackageType:index" }

packagetype_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:PackageType:show" }

packagetype_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:PackageType:new" }

packagetype_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:PackageType:create" }
    methods:  POST

packagetype_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:PackageType:edit" }

packagetype_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:PackageType:update" }
    methods:  [POST, PUT]

packagetype_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:PackageType:delete" }
    methods:  [POST, DELETE]
