playerstat:
    path:     /
    defaults: { _controller: "SportClubBundle:PlayerStat:index" }

playerstat_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:PlayerStat:show" }

playerstat_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:PlayerStat:new" }

playerstat_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:PlayerStat:create" }
    methods:  POST

playerstat_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:PlayerStat:edit" }

playerstat_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:PlayerStat:update" }
    methods:  [POST, PUT]

playerstat_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:PlayerStat:delete" }
    methods:  [POST, DELETE]
