pushdevice:
    path:     /
    defaults: { _controller: "SportClubBundle:PushDevice:index" }

pushdevice_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:PushDevice:show" }

pushdevice_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:PushDevice:new" }

pushdevice_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:PushDevice:create" }
    methods:  POST

pushdevice_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:PushDevice:edit" }

pushdevice_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:PushDevice:update" }
    methods:  [POST, PUT]

pushdevice_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:PushDevice:delete" }
    methods:  [POST, DELETE]
