pushmessage:
    path:     /
    defaults: { _controller: "SportClubBundle:PushMessage:index" }

pushmessage_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:PushMessage:show" }

pushmessage_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:PushMessage:new" }

pushmessage_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:PushMessage:create" }
    methods:  POST

pushmessage_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:PushMessage:edit" }

pushmessage_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:PushMessage:update" }
    methods:  [POST, PUT]

pushmessage_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:PushMessage:delete" }
    methods:  [POST, DELETE]
