quiz:
    path:     /
    defaults: { _controller: "SportClubBundle:Quiz:index" }

quiz_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:Quiz:show" }

quiz_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:Quiz:new" }

quiz_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:Quiz:create" }
    methods:  POST

quiz_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:Quiz:edit" }

quiz_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:Quiz:update" }
    methods:  [POST, PUT]

quiz_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:Quiz:delete" }
    methods:  [POST, DELETE]
