rating:
    path:     /
    defaults: { _controller: "SportClubBundle:Rating:index" }

rating_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:Rating:show" }

rating_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:Rating:new" }

rating_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:Rating:create" }
    methods:  POST

rating_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:Rating:edit" }

rating_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:Rating:update" }
    methods:  [POST, PUT]

rating_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:Rating:delete" }
    methods:  [POST, DELETE]
