scorer:
    path:     /
    defaults: { _controller: "SportClubBundle:Scorer:index" }

scorer_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:Scorer:show" }

scorer_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:Scorer:new" }

scorer_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:Scorer:create" }
    methods:  POST

scorer_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:Scorer:edit" }

scorer_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:Scorer:update" }
    methods:  [POST, PUT]

scorer_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:Scorer:delete" }
    methods:  [POST, DELETE]
