season:
    path:     /
    defaults: { _controller: "SportClubBundle:Season:index" }

season_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:Season:show" }

season_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:Season:new" }

season_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:Season:create" }
    methods:  POST

season_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:Season:edit" }

season_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:Season:update" }
    methods:  [POST, PUT]

season_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:Season:delete" }
    methods:  [POST, DELETE]
