sharing:
    path:     /
    defaults: { _controller: "SportClubBundle:Sharing:index" }

sharing_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:Sharing:show" }

sharing_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:Sharing:new" }

sharing_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:Sharing:create" }
    methods:  POST

sharing_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:Sharing:edit" }

sharing_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:Sharing:update" }
    methods:  [POST, PUT]

sharing_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:Sharing:delete" }
    methods:  [POST, DELETE]
