sport:
    path:     /
    defaults: { _controller: "SportClubBundle:Sport:index" }

sport_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:Sport:show" }

sport_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:Sport:new" }

sport_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:Sport:create" }
    methods:  POST

sport_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:Sport:edit" }

sport_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:Sport:update" }
    methods:  [POST, PUT]

sport_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:Sport:delete" }
    methods:  [POST, DELETE]
