sportevent:
    path:     /
    defaults: { _controller: "SportClubBundle:SportEvent:index" }

sportevent_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:SportEvent:show" }

sportevent_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:SportEvent:new" }

sportevent_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:SportEvent:create" }
    methods:  POST

sportevent_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:SportEvent:edit" }

sportevent_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:SportEvent:update" }
    methods:  [POST, PUT]

sportevent_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:SportEvent:delete" }
    methods:  [POST, DELETE]
