stat:
    path:     /
    defaults: { _controller: "SportClubBundle:Stat:index" }

stat_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:Stat:show" }

stat_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:Stat:new" }

stat_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:Stat:create" }
    methods:  POST

stat_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:Stat:edit" }

stat_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:Stat:update" }
    methods:  [POST, PUT]

stat_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:Stat:delete" }
    methods:  [POST, DELETE]
