store:
    path:     /
    defaults: { _controller: "SportClubBundle:Store:index" }

store_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:Store:show" }

store_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:Store:new" }

store_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:Store:create" }
    methods:  POST

store_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:Store:edit" }

store_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:Store:update" }
    methods:  [POST, PUT]

store_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:Store:delete" }
    methods:  [POST, DELETE]
