subscription:
    path:     /
    defaults: { _controller: "SportClubBundle:Subscription:index" }

subscription_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:Subscription:show" }

subscription_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:Subscription:new" }

subscription_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:Subscription:create" }
    methods:  POST

subscription_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:Subscription:edit" }

subscription_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:Subscription:update" }
    methods:  [POST, PUT]

subscription_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:Subscription:delete" }
    methods:  [POST, DELETE]
