user:
    path:     /
    defaults: { _controller: "SportClubBundle:User:index" }

user_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:User:show" }

user_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:User:new" }

user_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:User:create" }
    methods:  POST

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:User:edit" }

user_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:User:update" }
    methods:  [POST, PUT]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:User:delete" }
    methods:  [POST, DELETE]
