usersetting:
    path:     /
    defaults: { _controller: "SportClubBundle:UserSetting:index" }

usersetting_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:UserSetting:show" }

usersetting_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:UserSetting:new" }

usersetting_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:UserSetting:create" }
    methods:  POST

usersetting_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:UserSetting:edit" }

usersetting_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:UserSetting:update" }
    methods:  [POST, PUT]

usersetting_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:UserSetting:delete" }
    methods:  [POST, DELETE]
