videocategory:
    path:     /
    defaults: { _controller: "SportClubBundle:VideoCategory:index" }

videocategory_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:VideoCategory:show" }

videocategory_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:VideoCategory:new" }

videocategory_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:VideoCategory:create" }
    methods:  POST

videocategory_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:VideoCategory:edit" }

videocategory_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:VideoCategory:update" }
    methods:  [POST, PUT]

videocategory_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:VideoCategory:delete" }
    methods:  [POST, DELETE]
