videotype:
    path:     /
    defaults: { _controller: "SportClubBundle:VideoType:index" }

videotype_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:VideoType:show" }

videotype_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:VideoType:new" }

videotype_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:VideoType:create" }
    methods:  POST

videotype_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:VideoType:edit" }

videotype_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:VideoType:update" }
    methods:  [POST, PUT]

videotype_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:VideoType:delete" }
    methods:  [POST, DELETE]
