visit:
    path:     /
    defaults: { _controller: "SportClubBundle:Visit:index" }

visit_details:
    path:     /{id}/details
    defaults: { _controller: "SportClubBundle:Visit:show" }

visit_new:
    path:     /new
    defaults: { _controller: "SportClubBundle:Visit:new" }

visit_create:
    path:     /create
    defaults: { _controller: "SportClubBundle:Visit:create" }
    methods:  POST

visit_edit:
    path:     /{id}/edit
    defaults: { _controller: "SportClubBundle:Visit:edit" }

visit_update:
    path:     /{id}/update
    defaults: { _controller: "SportClubBundle:Visit:update" }
    methods:  [POST, PUT]

visit_delete:
    path:     /{id}/delete
    defaults: { _controller: "SportClubBundle:Visit:delete" }
    methods:  [POST, DELETE]
