# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html


imports:
    - { resource: "@UbidElectricityBundle/Resources/config/security.yml" }

security:

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_API:         ROLE_API
        ROLE_SUBSCRIBER:  [ROLE_API, ROLE_SUBSCRIBER]
        ROLE_ADMIN:  [ROLE_API, ROLE_ADMIN]
        ROLE_ADMIN_PUBLISHER:       [ROLE_API, ROLE_ADMIN_PUBLISHER]
        ROLE_SUPER_ADMIN: [ROLE_API, ROLE_SUPER_ADMIN]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        thumb:
            pattern:  ^/thumb
            stateless: true
            anonymous: true

        home_tenders:
            pattern: ^/(en|fr|ar)/api/v1/homeTenders
            stateless: true
            anonymous: true

        home_tender:
           pattern: ^/(en|fr|ar)/api/v1/homeTender
           stateless: true
           anonymous: true

        contact:
            pattern: ^/(en|fr|ar)/api/v1/contact
            stateless: true
            anonymous: true

        homeSectors:
            pattern: ^/(en|fr|ar)/api/v1/homeSectors
            stateless: true
            anonymous: true

        advanced_search:
            pattern: ^/api/sr
            stateless: true
            anonymous: true

        max_estimated_cost:
            pattern: ^/api/maxCost
            stateless: true
            anonymous: true

        categoriesTenders:
            pattern: ^/(en|fr|ar)/api/v1/categoriesTenders
            stateless: true
            anonymous: true

        register:
            pattern:  ^/(en|fr|ar)/api/v1/register
            stateless: true
            anonymous: true

        register_social:
            pattern:  ^/(en|fr|ar)/api/v1/socialRegister
            stateless: true
            anonymous: true

        checkEmail:
            pattern:  ^/(en|fr|ar)/api/v1/checkEmail
            stateless: true
            anonymous: true

        checkPhone:
            pattern:  ^/(en|fr|ar)/api/v1/checkPhone
            stateless: true
            anonymous: true

        countries:
            pattern:  ^/api/countries
            stateless: true
            anonymous: true

        languages:
            pattern: ^/api/languages
            stateless: true
            anonymous: true

        stores:
            pattern:  ^/(en|fr|ar)/api/v1/stores
            stateless: true
            anonymous: true

        storesCount:
            pattern:  ^/(en|fr|ar)/api/v1/storesCount
            stateless: true
            anonymous: true

        emailConfirm:
            pattern:  ^/(en|fr|ar)/api/v1/emailConfirm
            stateless: true
            anonymous: true

        requestResetPassword:
            pattern:  ^/(en|fr|ar)/api/v1/requestResetPassword
            stateless: true
            anonymous: true

        checkConfirmationToken:
            pattern:  ^/(en|fr|ar)/api/v1/checkConfirmationToken
            stateless: true
            anonymous: true

        reset:
            pattern:  ^/(en|fr|ar)/api/v1/reset
            stateless: true
            anonymous: true

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/login_check
                username_parameter:       email
                password_parameter:       password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        login_en:
            pattern:  ^/en/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /en/api/login_check
                username_parameter:       email
                password_parameter:       password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        login_fr:
            pattern:  ^/fr/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /fr/api/login_check
                username_parameter:       email
                password_parameter:       password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        login_ar:
            pattern:  ^/ar/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /ar/api/login_check
                username_parameter:       email
                password_parameter:       password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        api:
            pattern:   ^/api/
            stateless: true
            provider: fos_userbundle
            anonymous: false
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                cookie:               # check token in a cookie
                    enabled: false
                    name:    BEARER
                query_parameter:
                    enabled: true
                    name:    bearer
                throw_exceptions:        false
                create_entry_point:      true
                authentication_provider: lexik_jwt_authentication.security.authentication.provider
                authentication_listener: lexik_jwt_authentication.security.authentication.listener
        api_lang:
            pattern:   ^/(en|fr|ar)/api/v1/
            stateless: true
            provider: fos_userbundle
            anonymous: false
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                cookie:               # check token in a cookie
                    enabled: false
                    name:    BEARER
                query_parameter:
                    enabled: true
                    name:    bearer
                throw_exceptions:        false
                create_entry_point:      true
                authentication_provider: lexik_jwt_authentication.security.authentication.provider
                authentication_listener: lexik_jwt_authentication.security.authentication.listener
        efconnect:
            pattern:   ^/efconnect
            stateless: true
            provider: fos_userbundle
            anonymous: false
            lexik_jwt: 
                authorization_header: 
                    enabled: true
                    prefix:  Bearer
                cookie:               # check token in a cookie
                    enabled: false
                    name:    BEARER
                query_parameter:      
                    enabled: true
                    name:    bearer
                throw_exceptions:        false   
                create_entry_point:      true 
                authentication_provider: lexik_jwt_authentication.security.authentication.provider
                authentication_listener: lexik_jwt_authentication.security.authentication.listener
        
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                # csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true