collection:
    path:     /
    defaults: { _controller: "BiodyXpertBundle:Collection:index" }

collection_details:
    path:     /{id}/details
    defaults: { _controller: "BiodyXpertBundle:Collection:show" }

collection_new:
    path:     /new
    defaults: { _controller: "BiodyXpertBundle:Collection:new" }

collection_create:
    path:     /create
    defaults: { _controller: "BiodyXpertBundle:Collection:create" }
    methods:  POST

collection_edit:
    path:     /{id}/edit
    defaults: { _controller: "BiodyXpertBundle:Collection:edit" }

collection_update:
    path:     /{id}/update
    defaults: { _controller: "BiodyXpertBundle:Collection:update" }
    methods:  [POST, PUT]

collection_delete:
    path:     /{id}/delete
    defaults: { _controller: "BiodyXpertBundle:Collection:delete" }
    methods:  [POST, DELETE]
