document:
    path:     /
    defaults: { _controller: "BiodyXpertBundle:Document:index" }

document_details:
    path:     /{id}/details
    defaults: { _controller: "BiodyXpertBundle:Document:show" }

document_new:
    path:     /new
    defaults: { _controller: "BiodyXpertBundle:Document:new" }

document_create:
    path:     /create
    defaults: { _controller: "BiodyXpertBundle:Document:create" }
    methods:  POST

document_edit:
    path:     /{id}/edit
    defaults: { _controller: "BiodyXpertBundle:Document:edit" }

document_update:
    path:     /{id}/update
    defaults: { _controller: "BiodyXpertBundle:Document:update" }
    methods:  [POST, PUT]

document_delete:
    path:     /{id}/delete
    defaults: { _controller: "BiodyXpertBundle:Document:delete" }
    methods:  [POST, DELETE]
