indicatortype:
    path:     /
    defaults: { _controller: "BiodyXpertBundle:IndicatorType:index" }

indicatortype_details:
    path:     /{id}/details
    defaults: { _controller: "BiodyXpertBundle:IndicatorType:show" }

indicatortype_new:
    path:     /new
    defaults: { _controller: "BiodyXpertBundle:IndicatorType:new" }

indicatortype_create:
    path:     /create
    defaults: { _controller: "BiodyXpertBundle:IndicatorType:create" }
    methods:  POST

indicatortype_edit:
    path:     /{id}/edit
    defaults: { _controller: "BiodyXpertBundle:IndicatorType:edit" }

indicatortype_update:
    path:     /{id}/update
    defaults: { _controller: "BiodyXpertBundle:IndicatorType:update" }
    methods:  [POST, PUT]

indicatortype_delete:
    path:     /{id}/delete
    defaults: { _controller: "BiodyXpertBundle:IndicatorType:delete" }
    methods:  [POST, DELETE]
