indicator:
    path:     /
    defaults: { _controller: "BiodyXpertBundle:Indicator:index" }

indicator_details:
    path:     /{id}/details
    defaults: { _controller: "BiodyXpertBundle:Indicator:show" }

indicator_new:
    path:     /new
    defaults: { _controller: "BiodyXpertBundle:Indicator:new" }

indicator_create:
    path:     /create
    defaults: { _controller: "BiodyXpertBundle:Indicator:create" }
    methods:  POST

indicator_edit:
    path:     /{id}/edit
    defaults: { _controller: "BiodyXpertBundle:Indicator:edit" }

indicator_update:
    path:     /{id}/update
    defaults: { _controller: "BiodyXpertBundle:Indicator:update" }
    methods:  [POST, PUT]

indicator_delete:
    path:     /{id}/delete
    defaults: { _controller: "BiodyXpertBundle:Indicator:delete" }
    methods:  [POST, DELETE]
