licencetype:
    path:     /
    defaults: { _controller: "BiodyXpertBundle:LicenceType:index" }

licencetype_details:
    path:     /{id}/details
    defaults: { _controller: "BiodyXpertBundle:LicenceType:show" }

licencetype_new:
    path:     /new
    defaults: { _controller: "BiodyXpertBundle:LicenceType:new" }

licencetype_create:
    path:     /create
    defaults: { _controller: "BiodyXpertBundle:LicenceType:create" }
    methods:  POST

licencetype_edit:
    path:     /{id}/edit
    defaults: { _controller: "BiodyXpertBundle:LicenceType:edit" }

licencetype_update:
    path:     /{id}/update
    defaults: { _controller: "BiodyXpertBundle:LicenceType:update" }
    methods:  [POST, PUT]

licencetype_delete:
    path:     /{id}/delete
    defaults: { _controller: "BiodyXpertBundle:LicenceType:delete" }
    methods:  [POST, DELETE]
