note:
    path:     /
    defaults: { _controller: "BiodyXpertBundle:Note:index" }

note_details:
    path:     /{id}/details
    defaults: { _controller: "BiodyXpertBundle:Note:show" }

note_new:
    path:     /new
    defaults: { _controller: "BiodyXpertBundle:Note:new" }

note_create:
    path:     /create
    defaults: { _controller: "BiodyXpertBundle:Note:create" }
    methods:  POST

note_edit:
    path:     /{id}/edit
    defaults: { _controller: "BiodyXpertBundle:Note:edit" }

note_update:
    path:     /{id}/update
    defaults: { _controller: "BiodyXpertBundle:Note:update" }
    methods:  [POST, PUT]

note_delete:
    path:     /{id}/delete
    defaults: { _controller: "BiodyXpertBundle:Note:delete" }
    methods:  [POST, DELETE]
