patient:
    path:     /
    defaults: { _controller: "BiodyXpertBundle:Patient:index" }

patient_details:
    path:     /{id}/details
    defaults: { _controller: "BiodyXpertBundle:Patient:show" }

patient_new:
    path:     /new
    defaults: { _controller: "BiodyXpertBundle:Patient:new" }

patient_create:
    path:     /create
    defaults: { _controller: "BiodyXpertBundle:Patient:create" }
    methods:  POST

patient_edit:
    path:     /{id}/edit
    defaults: { _controller: "BiodyXpertBundle:Patient:edit" }

patient_update:
    path:     /{id}/update
    defaults: { _controller: "BiodyXpertBundle:Patient:update" }
    methods:  [POST, PUT]

patient_delete:
    path:     /{id}/delete
    defaults: { _controller: "BiodyXpertBundle:Patient:delete" }
    methods:  [POST, DELETE]
