patientgroup:
    path:     /
    defaults: { _controller: "BiodyXpertBundle:PatientGroup:index" }

patientgroup_details:
    path:     /{id}/details
    defaults: { _controller: "BiodyXpertBundle:PatientGroup:show" }

patientgroup_new:
    path:     /new
    defaults: { _controller: "BiodyXpertBundle:PatientGroup:new" }

patientgroup_create:
    path:     /create
    defaults: { _controller: "BiodyXpertBundle:PatientGroup:create" }
    methods:  POST

patientgroup_edit:
    path:     /{id}/edit
    defaults: { _controller: "BiodyXpertBundle:PatientGroup:edit" }

patientgroup_update:
    path:     /{id}/update
    defaults: { _controller: "BiodyXpertBundle:PatientGroup:update" }
    methods:  [POST, PUT]

patientgroup_delete:
    path:     /{id}/delete
    defaults: { _controller: "BiodyXpertBundle:PatientGroup:delete" }
    methods:  [POST, DELETE]
