translationindicatortype:
    path:     /
    defaults: { _controller: "BiodyXpertBundle:TranslationIndicatorType:index" }

translationindicatortype_details:
    path:     /{id}/details
    defaults: { _controller: "BiodyXpertBundle:TranslationIndicatorType:show" }

translationindicatortype_new:
    path:     /new
    defaults: { _controller: "BiodyXpertBundle:TranslationIndicatorType:new" }

translationindicatortype_create:
    path:     /create
    defaults: { _controller: "BiodyXpertBundle:TranslationIndicatorType:create" }
    methods:  POST

translationindicatortype_edit:
    path:     /{id}/edit
    defaults: { _controller: "BiodyXpertBundle:TranslationIndicatorType:edit" }

translationindicatortype_update:
    path:     /{id}/update
    defaults: { _controller: "BiodyXpertBundle:TranslationIndicatorType:update" }
    methods:  [POST, PUT]

translationindicatortype_delete:
    path:     /{id}/delete
    defaults: { _controller: "BiodyXpertBundle:TranslationIndicatorType:delete" }
    methods:  [POST, DELETE]
