translationfaqcategory:
    path:     /
    defaults: { _controller: "BiodyXpertBundle:TranslationFaqCategory:index" }

translationfaqcategory_details:
    path:     /{id}/details
    defaults: { _controller: "BiodyXpertBundle:TranslationFaqCategory:show" }

translationfaqcategory_new:
    path:     /new
    defaults: { _controller: "BiodyXpertBundle:TranslationFaqCategory:new" }

translationfaqcategory_create:
    path:     /create
    defaults: { _controller: "BiodyXpertBundle:TranslationFaqCategory:create" }
    methods:  POST

translationfaqcategory_edit:
    path:     /{id}/edit
    defaults: { _controller: "BiodyXpertBundle:TranslationFaqCategory:edit" }

translationfaqcategory_update:
    path:     /{id}/update
    defaults: { _controller: "BiodyXpertBundle:TranslationFaqCategory:update" }
    methods:  [POST, PUT]

translationfaqcategory_delete:
    path:     /{id}/delete
    defaults: { _controller: "BiodyXpertBundle:TranslationFaqCategory:delete" }
    methods:  [POST, DELETE]
