translationpatientgroup:
    path:     /
    defaults: { _controller: "BiodyXpertBundle:TranslationPatientGroup:index" }

translationpatientgroup_details:
    path:     /{id}/details
    defaults: { _controller: "BiodyXpertBundle:TranslationPatientGroup:show" }

translationpatientgroup_new:
    path:     /new
    defaults: { _controller: "BiodyXpertBundle:TranslationPatientGroup:new" }

translationpatientgroup_create:
    path:     /create
    defaults: { _controller: "BiodyXpertBundle:TranslationPatientGroup:create" }
    methods:  POST

translationpatientgroup_edit:
    path:     /{id}/edit
    defaults: { _controller: "BiodyXpertBundle:TranslationPatientGroup:edit" }

translationpatientgroup_update:
    path:     /{id}/update
    defaults: { _controller: "BiodyXpertBundle:TranslationPatientGroup:update" }
    methods:  [POST, PUT]

translationpatientgroup_delete:
    path:     /{id}/delete
    defaults: { _controller: "BiodyXpertBundle:TranslationPatientGroup:delete" }
    methods:  [POST, DELETE]
