translationpathology:
    path:     /
    defaults: { _controller: "BiodyXpertBundle:TranslationPathology:index" }

translationpathology_details:
    path:     /{id}/details
    defaults: { _controller: "BiodyXpertBundle:TranslationPathology:show" }

translationpathology_new:
    path:     /new
    defaults: { _controller: "BiodyXpertBundle:TranslationPathology:new" }

translationpathology_create:
    path:     /create
    defaults: { _controller: "BiodyXpertBundle:TranslationPathology:create" }
    methods:  POST

translationpathology_edit:
    path:     /{id}/edit
    defaults: { _controller: "BiodyXpertBundle:TranslationPathology:edit" }

translationpathology_update:
    path:     /{id}/update
    defaults: { _controller: "BiodyXpertBundle:TranslationPathology:update" }
    methods:  [POST, PUT]

translationpathology_delete:
    path:     /{id}/delete
    defaults: { _controller: "BiodyXpertBundle:TranslationPathology:delete" }
    methods:  [POST, DELETE]
