translationtemplate:
    path:     /
    defaults: { _controller: "BiodyXpertBundle:TranslationTemplate:index" }

translationtemplate_details:
    path:     /{id}/details
    defaults: { _controller: "BiodyXpertBundle:TranslationTemplate:show" }

translationtemplate_new:
    path:     /new
    defaults: { _controller: "BiodyXpertBundle:TranslationTemplate:new" }

translationtemplate_create:
    path:     /create
    defaults: { _controller: "BiodyXpertBundle:TranslationTemplate:create" }
    methods:  POST

translationtemplate_edit:
    path:     /{id}/edit
    defaults: { _controller: "BiodyXpertBundle:TranslationTemplate:edit" }

translationtemplate_update:
    path:     /{id}/update
    defaults: { _controller: "BiodyXpertBundle:TranslationTemplate:update" }
    methods:  [POST, PUT]

translationtemplate_delete:
    path:     /{id}/delete
    defaults: { _controller: "BiodyXpertBundle:TranslationTemplate:delete" }
    methods:  [POST, DELETE]
