translationcountry:
    path:     /
    defaults: { _controller: "BiodyXpertBundle:TranslationCountry:index" }

translationcountry_details:
    path:     /{id}/details
    defaults: { _controller: "BiodyXpertBundle:TranslationCountry:show" }

translationcountry_new:
    path:     /new
    defaults: { _controller: "BiodyXpertBundle:TranslationCountry:new" }

translationcountry_create:
    path:     /create
    defaults: { _controller: "BiodyXpertBundle:TranslationCountry:create" }
    methods:  POST

translationcountry_edit:
    path:     /{id}/edit
    defaults: { _controller: "BiodyXpertBundle:TranslationCountry:edit" }

translationcountry_update:
    path:     /{id}/update
    defaults: { _controller: "BiodyXpertBundle:TranslationCountry:update" }
    methods:  [POST, PUT]

translationcountry_delete:
    path:     /{id}/delete
    defaults: { _controller: "BiodyXpertBundle:TranslationCountry:delete" }
    methods:  [POST, DELETE]
