group:
    path:     /
    defaults: { _controller: "UbidElectricityBundle:Group:index" }

group_details:
    path:     /{id}/details
    defaults: { _controller: "UbidElectricityBundle:Group:show" }

group_new:
    path:     /new
    defaults: { _controller: "UbidElectricityBundle:Group:new" }

group_create:
    path:     /create
    defaults: { _controller: "UbidElectricityBundle:Group:create" }
    methods:  POST

group_edit:
    path:     /{id}/edit
    defaults: { _controller: "UbidElectricityBundle:Group:edit" }

group_update:
    path:     /{id}/update
    defaults: { _controller: "UbidElectricityBundle:Group:update" }
    methods:  [POST, PUT]

group_delete:
    path:     /{id}/delete
    defaults: { _controller: "UbidElectricityBundle:Group:delete" }
    methods:  [POST, DELETE]
