posttype:
    path:     /
    defaults: { _controller: "UbidElectricityBundle:PostType:index" }

posttype_details:
    path:     /{id}/details
    defaults: { _controller: "UbidElectricityBundle:PostType:show" }

posttype_new:
    path:     /new
    defaults: { _controller: "UbidElectricityBundle:PostType:new" }

posttype_create:
    path:     /create
    defaults: { _controller: "UbidElectricityBundle:PostType:create" }
    methods:  POST

posttype_edit:
    path:     /{id}/edit
    defaults: { _controller: "UbidElectricityBundle:PostType:edit" }

posttype_update:
    path:     /{id}/update
    defaults: { _controller: "UbidElectricityBundle:PostType:update" }
    methods:  [POST, PUT]

posttype_delete:
    path:     /{id}/delete
    defaults: { _controller: "UbidElectricityBundle:PostType:delete" }
    methods:  [POST, DELETE]
