producttype:
    path:     /
    defaults: { _controller: "UbidElectricityBundle:ProductType:index" }

producttype_details:
    path:     /{id}/details
    defaults: { _controller: "UbidElectricityBundle:ProductType:show" }

producttype_new:
    path:     /new
    defaults: { _controller: "UbidElectricityBundle:ProductType:new" }

producttype_create:
    path:     /create
    defaults: { _controller: "UbidElectricityBundle:ProductType:create" }
    methods:  POST

producttype_edit:
    path:     /{id}/edit
    defaults: { _controller: "UbidElectricityBundle:ProductType:edit" }

producttype_update:
    path:     /{id}/update
    defaults: { _controller: "UbidElectricityBundle:ProductType:update" }
    methods:  [POST, PUT]

producttype_delete:
    path:     /{id}/delete
    defaults: { _controller: "UbidElectricityBundle:ProductType:delete" }
    methods:  [POST, DELETE]
