supplier:
    path:     /
    defaults: { _controller: "UbidElectricityBundle:Supplier:index" }

supplier_details:
    path:     /{id}/details
    defaults: { _controller: "UbidElectricityBundle:Supplier:show" }

supplier_new:
    path:     /new
    defaults: { _controller: "UbidElectricityBundle:Supplier:new" }

supplier_create:
    path:     /create
    defaults: { _controller: "UbidElectricityBundle:Supplier:create" }
    methods:  POST

supplier_edit:
    path:     /{id}/edit
    defaults: { _controller: "UbidElectricityBundle:Supplier:edit" }

supplier_update:
    path:     /{id}/update
    defaults: { _controller: "UbidElectricityBundle:Supplier:update" }
    methods:  [POST, PUT]

supplier_delete:
    path:     /{id}/delete
    defaults: { _controller: "UbidElectricityBundle:Supplier:delete" }
    methods:  [POST, DELETE]
