banner:
    path:     /
    defaults: { _controller: "BucksHunterBundle:Banner:index" }

banner_details:
    path:     /{id}/details
    defaults: { _controller: "BucksHunterBundle:Banner:show" }

banner_new:
    path:     /new
    defaults: { _controller: "BucksHunterBundle:Banner:new" }

banner_create:
    path:     /create
    defaults: { _controller: "BucksHunterBundle:Banner:create" }
    methods:  POST

banner_edit:
    path:     /{id}/edit
    defaults: { _controller: "BucksHunterBundle:Banner:edit" }

banner_update:
    path:     /{id}/update
    defaults: { _controller: "BucksHunterBundle:Banner:update" }
    methods:  [POST, PUT]

banner_delete:
    path:     /{id}/delete
    defaults: { _controller: "BucksHunterBundle:Banner:delete" }
    methods:  [POST, DELETE]
