score:
    path:     /
    defaults: { _controller: "BucksHunterBundle:Score:index" }

score_details:
    path:     /{id}/details
    defaults: { _controller: "BucksHunterBundle:Score:show" }

score_new:
    path:     /new
    defaults: { _controller: "BucksHunterBundle:Score:new" }

score_create:
    path:     /create
    defaults: { _controller: "BucksHunterBundle:Score:create" }
    methods:  POST

score_edit:
    path:     /{id}/edit
    defaults: { _controller: "BucksHunterBundle:Score:edit" }

score_update:
    path:     /{id}/update
    defaults: { _controller: "BucksHunterBundle:Score:update" }
    methods:  [POST, PUT]

score_delete:
    path:     /{id}/delete
    defaults: { _controller: "BucksHunterBundle:Score:delete" }
    methods:  [POST, DELETE]
