session:
    path:     /
    defaults: { _controller: "BucksHunterBundle:Session:index" }

session_details:
    path:     /{id}/details
    defaults: { _controller: "BucksHunterBundle:Session:show" }

session_new:
    path:     /new
    defaults: { _controller: "BucksHunterBundle:Session:new" }

session_create:
    path:     /create
    defaults: { _controller: "BucksHunterBundle:Session:create" }
    methods:  POST

session_edit:
    path:     /{id}/edit
    defaults: { _controller: "BucksHunterBundle:Session:edit" }

session_update:
    path:     /{id}/update
    defaults: { _controller: "BucksHunterBundle:Session:update" }
    methods:  [POST, PUT]

session_delete:
    path:     /{id}/delete
    defaults: { _controller: "BucksHunterBundle:Session:delete" }
    methods:  [POST, DELETE]
