
bucks_hunter:
    resource: "@BucksHunterBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

thumb:
    resource: "@BucksHunterBundle/Controller/ThumbController.php"
    type:     annotation
    prefix:   /

api_login_check:
    path: /api/login_check

api_login_check_lang:
    path: /{_locale}/api/login_check
    requirements:
        _locale: en|fr|ar

bucks_hunter_v1_api:
    resource: "@BucksHunterBundle/Controller/ApiV1RESTController.php"
    type:   rest
    prefix:   /{_locale}/api/v1
    requirements:
        _locale: en|fr|ar

bucks_hunter_banner_api:
    resource: "@BucksHunterBundle/Controller/BannerRESTController.php"
    type:   rest
    prefix:   /api

bucks_hunter_country_api:
    resource: "@BucksHunterBundle/Controller/CountryRESTController.php"
    type:   rest
    prefix:   /api

bucks_hunter_game_api:
    resource: "@BucksHunterBundle/Controller/GameRESTController.php"
    type:   rest
    prefix:   /api

bucks_hunter_language_api:
    resource: "@BucksHunterBundle/Controller/LanguageRESTController.php"
    type:   rest
    prefix:   /api

bucks_hunter_push_device_api:
    resource: "@BucksHunterBundle/Controller/PushDeviceRESTController.php"
    type:   rest
    prefix:   /api

bucks_hunter_push_message_api:
    resource: "@BucksHunterBundle/Controller/PushMessageRESTController.php"
    type:   rest
    prefix:   /api

bucks_hunter_push_notification_api:
    resource: "@BucksHunterBundle/Controller/PushNotificationRESTController.php"
    type:   rest
    prefix:   /api

push_notification_sender:
    resource: "@BucksHunterBundle/Controller/PushNotificationSenderController.php"
    type:     rest
    prefix:   /api

bucks_hunter_puzzle_api:
    resource: "@BucksHunterBundle/Controller/PuzzleRESTController.php"
    type:   rest
    prefix:   /api

bucks_hunter_score_api:
    resource: "@BucksHunterBundle/Controller/ScoreRESTController.php"
    type:   rest
    prefix:   /api

bucks_hunter_session_api:
    resource: "@BucksHunterBundle/Controller/SessionRESTController.php"
    type:   rest
    prefix:   /api

bucks_hunter_user_api:
    resource: "@BucksHunterBundle/Controller/UserRESTController.php"
    type:   rest
    prefix:   /api

bucks_hunter_banner:
    resource: "@BucksHunterBundle/Resources/config/routing/banner.yml"
    prefix:   /banner

bucks_hunter_country:
    resource: "@BucksHunterBundle/Resources/config/routing/country.yml"
    prefix:   /country

bucks_hunter_game:
    resource: "@BucksHunterBundle/Resources/config/routing/game.yml"
    prefix:   /game

bucks_hunter_language:
    resource: "@BucksHunterBundle/Resources/config/routing/language.yml"
    prefix:   /language

bucks_hunter_push_device:
    resource: "@BucksHunterBundle/Resources/config/routing/push_device.yml"
    prefix:   /push-device

bucks_hunter_push_message:
    resource: "@BucksHunterBundle/Resources/config/routing/push_message.yml"
    prefix:   /push-message

bucks_hunter_push_notification:
    resource: "@BucksHunterBundle/Resources/config/routing/push_notification.yml"
    prefix:   /push-notification

bucks_hunter_puzzle:
    resource: "@BucksHunterBundle/Resources/config/routing/puzzle.yml"
    prefix:   /puzzle

bucks_hunter_score:
    resource: "@BucksHunterBundle/Resources/config/routing/score.yml"
    prefix:   /score

bucks_hunter_session:
    resource: "@BucksHunterBundle/Resources/config/routing/session.yml"
    prefix:   /session

bucks_hunter_user:
    resource: "@BucksHunterBundle/Resources/config/routing/user.yml"
    prefix:   /user

