
biody_xpert:
    resource: "@BiodyXpertBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

thumb:
    resource: "@BiodyXpertBundle/Controller/ThumbController.php"
    type:     annotation
    prefix:   /

api_login_check:
    path: /api/login_check

api_login_check_lang:
    path: /{_locale}/api/login_check
    requirements:
        _locale: en|fr|ar

biody_xpert_v1_api:
    resource: "@BiodyXpertBundle/Controller/ApiV1RESTController.php"
    type:   rest
    prefix:   /{_locale}/api/v1
    requirements:
        _locale: en|fr|ar

biody_xpert_dashboard:
    resource: "@BiodyXpertBundle/Controller/DashboardRESTController.php"
    type:   rest
    prefix:   /{_locale}/api/dashboard
    requirements:
        _locale: en|fr|ar

biody_xpert_reporting:
    resource: "@BiodyXpertBundle/Controller/ReportingRESTController.php"
    type:   rest
    prefix:   /{_locale}/api/reporting
    requirements:
        _locale: en|fr|ar

biody_xpert_appointment_api:
    resource: "@BiodyXpertBundle/Controller/AppointmentRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_author_api:
    resource: "@BiodyXpertBundle/Controller/AuthorRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_collection_api:
    resource: "@BiodyXpertBundle/Controller/CollectionRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_country_api:
    resource: "@BiodyXpertBundle/Controller/CountryRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_device_serial_number_api:
    resource: "@BiodyXpertBundle/Controller/DeviceSerialNumberRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_user_api:
    resource: "@BiodyXpertBundle/Controller/UserRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_document_api:
    resource: "@BiodyXpertBundle/Controller/DocumentRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_document_category_api:
    resource: "@BiodyXpertBundle/Controller/DocumentCategoryRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_document_type_api:
    resource: "@BiodyXpertBundle/Controller/DocumentTypeRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_faq_api:
    resource: "@BiodyXpertBundle/Controller/FaqRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_faq_category_api:
    resource: "@BiodyXpertBundle/Controller/FaqCategoryRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_group_api:
    resource: "@BiodyXpertBundle/Controller/GroupRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_indicator_api:
    resource: "@BiodyXpertBundle/Controller/IndicatorRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_indicator_type_api:
    resource: "@BiodyXpertBundle/Controller/IndicatorTypeRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_instance_api:
    resource: "@BiodyXpertBundle/Controller/InstanceRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_language_api:
    resource: "@BiodyXpertBundle/Controller/LanguageRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_licence_api:
    resource: "@BiodyXpertBundle/Controller/LicenceRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_licence_type_api:
    resource: "@BiodyXpertBundle/Controller/LicenceTypeRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_log_api:
    resource: "@BiodyXpertBundle/Controller/LogRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_measurement_api:
    resource: "@BiodyXpertBundle/Controller/MeasurementRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
measurement_interpretation:
    resource: "@BiodyXpertBundle/Controller/InterpretMeasurementController.php"
    type:     rest
    prefix:   /api

biody_xpert_note_api:
    resource: "@BiodyXpertBundle/Controller/NoteRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_notification_api:
    resource: "@BiodyXpertBundle/Controller/NotificationRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_pathology_api:
    resource: "@BiodyXpertBundle/Controller/PathologyRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_patient_api:
    resource: "@BiodyXpertBundle/Controller/PatientRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
patient_importer:
    resource: "@BiodyXpertBundle/Controller/PatientImporterController.php"
    type:     rest
    prefix:   /api

patient_exporter:
    resource: "@BiodyXpertBundle/Controller/PatientExporterController.php"
    type:     rest
    prefix:   /api

biody_xpert_patient_group_api:
    resource: "@BiodyXpertBundle/Controller/PatientGroupRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_physical_activity_api:
    resource: "@BiodyXpertBundle/Controller/PhysicalActivityRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_session_api:
    resource: "@BiodyXpertBundle/Controller/SessionRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_template_api:
    resource: "@BiodyXpertBundle/Controller/TemplateRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_translation_country_api:
    resource: "@BiodyXpertBundle/Controller/TranslationCountryRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_translation_faq_api:
    resource: "@BiodyXpertBundle/Controller/TranslationFaqRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_translation_faq_category_api:
    resource: "@BiodyXpertBundle/Controller/TranslationFaqCategoryRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_translation_indicator_type_api:
    resource: "@BiodyXpertBundle/Controller/TranslationIndicatorTypeRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_translation_pathology_api:
    resource: "@BiodyXpertBundle/Controller/TranslationPathologyRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_translation_patient_group_api:
    resource: "@BiodyXpertBundle/Controller/TranslationPatientGroupRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_translation_physical_activity_api:
    resource: "@BiodyXpertBundle/Controller/TranslationPhysicalActivityRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_translation_template_api:
    resource: "@BiodyXpertBundle/Controller/TranslationTemplateRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_translation_word_api:
    resource: "@BiodyXpertBundle/Controller/TranslationWordRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_variable_api:
    resource: "@BiodyXpertBundle/Controller/VariableRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_word_api:
    resource: "@BiodyXpertBundle/Controller/WordRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
biody_xpert_appointment:
    resource: "@BiodyXpertBundle/Resources/config/routing/appointment.yml"
    prefix:   /appointment

biody_xpert_author:
    resource: "@BiodyXpertBundle/Resources/config/routing/author.yml"
    prefix:   /author

biody_xpert_collection:
    resource: "@BiodyXpertBundle/Resources/config/routing/collection.yml"
    prefix:   /collection

biody_xpert_country:
    resource: "@BiodyXpertBundle/Resources/config/routing/country.yml"
    prefix:   /country

biody_xpert_device_serial_number:
    resource: "@BiodyXpertBundle/Resources/config/routing/device_serial_number.yml"
    prefix:   /device-serial-number

biody_xpert_user:
    resource: "@BiodyXpertBundle/Resources/config/routing/user.yml"
    prefix:   /user

biody_xpert_document:
    resource: "@BiodyXpertBundle/Resources/config/routing/document.yml"
    prefix:   /document

biody_xpert_document_category:
    resource: "@BiodyXpertBundle/Resources/config/routing/document_category.yml"
    prefix:   /document-category

biody_xpert_document_type:
    resource: "@BiodyXpertBundle/Resources/config/routing/document_type.yml"
    prefix:   /document-type

biody_xpert_faq:
    resource: "@BiodyXpertBundle/Resources/config/routing/faq.yml"
    prefix:   /faq

biody_xpert_faq_category:
    resource: "@BiodyXpertBundle/Resources/config/routing/faq_category.yml"
    prefix:   /faq-category

biody_xpert_group:
    resource: "@BiodyXpertBundle/Resources/config/routing/group.yml"
    prefix:   /group

biody_xpert_indicator:
    resource: "@BiodyXpertBundle/Resources/config/routing/indicator.yml"
    prefix:   /indicator

biody_xpert_indicator_type:
    resource: "@BiodyXpertBundle/Resources/config/routing/indicator_type.yml"
    prefix:   /indicator-type

biody_xpert_instance:
    resource: "@BiodyXpertBundle/Resources/config/routing/instance.yml"
    prefix:   /instance

biody_xpert_language:
    resource: "@BiodyXpertBundle/Resources/config/routing/language.yml"
    prefix:   /language

biody_xpert_licence:
    resource: "@BiodyXpertBundle/Resources/config/routing/licence.yml"
    prefix:   /licence

biody_xpert_licence_type:
    resource: "@BiodyXpertBundle/Resources/config/routing/licence_type.yml"
    prefix:   /licence-type

biody_xpert_log:
    resource: "@BiodyXpertBundle/Resources/config/routing/log.yml"
    prefix:   /log

biody_xpert_measurement:
    resource: "@BiodyXpertBundle/Resources/config/routing/measurement.yml"
    prefix:   /measurement

biody_xpert_note:
    resource: "@BiodyXpertBundle/Resources/config/routing/note.yml"
    prefix:   /note

biody_xpert_notification:
    resource: "@BiodyXpertBundle/Resources/config/routing/notification.yml"
    prefix:   /notification

biody_xpert_pathology:
    resource: "@BiodyXpertBundle/Resources/config/routing/pathology.yml"
    prefix:   /pathology

biody_xpert_patient:
    resource: "@BiodyXpertBundle/Resources/config/routing/patient.yml"
    prefix:   /patient

biody_xpert_patient_group:
    resource: "@BiodyXpertBundle/Resources/config/routing/patient_group.yml"
    prefix:   /patient-group

biody_xpert_physical_activity:
    resource: "@BiodyXpertBundle/Resources/config/routing/physical_activity.yml"
    prefix:   /physical-activity

biody_xpert_session:
    resource: "@BiodyXpertBundle/Resources/config/routing/session.yml"
    prefix:   /session

biody_xpert_template:
    resource: "@BiodyXpertBundle/Resources/config/routing/template.yml"
    prefix:   /template

biody_xpert_translation_country:
    resource: "@BiodyXpertBundle/Resources/config/routing/translation_country.yml"
    prefix:   /translation-country

biody_xpert_translation_faq:
    resource: "@BiodyXpertBundle/Resources/config/routing/translation_faq.yml"
    prefix:   /translation-faq

biody_xpert_translation_faq_category:
    resource: "@BiodyXpertBundle/Resources/config/routing/translation_faq_category.yml"
    prefix:   /translation-faq-category

biody_xpert_translation_indicator_type:
    resource: "@BiodyXpertBundle/Resources/config/routing/translation_indicator_type.yml"
    prefix:   /translation-indicator-type

biody_xpert_translation_pathology:
    resource: "@BiodyXpertBundle/Resources/config/routing/translation_pathology.yml"
    prefix:   /translation-pathology

biody_xpert_translation_patient_group:
    resource: "@BiodyXpertBundle/Resources/config/routing/translation_patient_group.yml"
    prefix:   /translation-patient-group

biody_xpert_translation_physical_activity:
    resource: "@BiodyXpertBundle/Resources/config/routing/translation_physical_activity.yml"
    prefix:   /translation-physical-activity

biody_xpert_translation_template:
    resource: "@BiodyXpertBundle/Resources/config/routing/translation_template.yml"
    prefix:   /translation-template

biody_xpert_translation_word:
    resource: "@BiodyXpertBundle/Resources/config/routing/translation_word.yml"
    prefix:   /translation-word

biody_xpert_variable:
    resource: "@BiodyXpertBundle/Resources/config/routing/variable.yml"
    prefix:   /variable

biody_xpert_word:
    resource: "@BiodyXpertBundle/Resources/config/routing/word.yml"
    prefix:   /word

