e_electricity_front_locale_home:
    path: /
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_login:
    path: /login/
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_login_type:
    path: /login/{type}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_logout:
    path: /logout
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_register:
    path: /register/
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_register_type:
    path: /register/{type}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_resetpassword:
    path: /reset-password
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_emailconfirm:
    path: /auth/email-confirm/{token}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_reset:
    path: /auth/reset/{token}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_lockscreen:
    path: /lock-screen
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_profile:
    path: /profile
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_usermenu:
    path: /user-menu
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_changepassword:
    path: /change-password
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_buyers:
    path: /buyers
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_buyers_category:
    path: /buyers/{slug}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_buyer:
    path: /buyer/{id}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_suppliers:
    path: /suppliers
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_suppliers_category:
    path: /suppliers/{slug}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_supplier:
    path: /supplier/{id}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_tenders:
    path: /tenders/
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_tenders_section:
    path: /tenders/{section}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_tender:
    path: /tender/{id}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_tenders_sector:
    path: /tenders/sector/{id}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_tenders_category:
    path: /tenders/{section}/{slug}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_tenders_country:
    path: /tenders/country/{id}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_advanced_search:
    path: /advanced-search-results
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_generic_search:
    path: /generic-search-results
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_apply_tender:
    path: /apply_tender/{id}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_mytenders:
    path: /my-tenders
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_mytenders_details:
    path: /my-tenders/details/{id}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_mytenders_edit:
    path: /my-tenders/edit/{id}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_mytenders_new:
    path: /my-tenders/new
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_mytenders_list:
    path: /my-tenders/list
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_products:
    path: /products
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_product:
    path: /product/{categorySlug}/{slug}/{id}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_myproducts:
    path: /my-products
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_myproducts_details:
    path: /my-products/details/{id}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_myproducts_edit:
    path: /my-products/edit/{id}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_myproducts_new:
    path: /my-products/new
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_myproducts_list:
    path: /my-products/list
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_mybids:
    path: /my-bids
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_mybids_list:
    path: /my-bids/list
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_mybids_details:
    path: /my-bids/details/{id}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_mybids_edit:
    path: /my-bids/edit/{id}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_mybids_new:
    path: /my-bids/new
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_bookmarkproject:
    path: /bookmark-project
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_bookmarkproject_list:
    path: /bookmark-project/list
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_bookmarkproject_details:
    path: /details/{id}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_mybuyers:
    path: /my-buyers
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_mybuyers_details:
    path: /my-buyers/details/{id}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_mybuyers_edit:
    path: /my-buyers/edit/{id}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_mybuyers_new:
    path: /my-buyers/new
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_mybuyers_list:
    path: /my-buyers/list
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_mysuppliers:
    path: /my-suppliers
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_mysuppliers_details:
    path: /my-suppliers/details/{id}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_mysuppliers_edit:
    path: /my-suppliers/edit/{id}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_mysuppliers_new:
    path: /my-suppliers/new
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_mysuppliers_list:
    path: /my-suppliers/list
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_contact:
    path: /contact
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_post:
    path: /post/{slug}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_projectbids:
    path: /project-bids
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_projectbids_list:
    path: /project-bids/list
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_projectbids_list:
    path: /list
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_projectbids_bids:
    path: /project-bids/bids-by-project/{projectId}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_projectbids_bids_details:
    path: /project-bids/details/title-tender/{bidId}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_projectbids_bid:
    path: /details/{slug}/{id}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_projectbids_shortlist:
    path: /short-list
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_myAlerts:
    path: /my-alerts
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_myAlerts_list:
    path: /my-alerts/list
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_myAlerts_details:
    path: /my-alerts/details/{id}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_myAlerts_new:
    path: /my-alerts/new
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_myAlerts_edit:
    path: /my-alerts/edit/{id}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_myAlerts_settings:
    path: /my-alerts/settings
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_categories:
    path: /categories
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_category:
    path: /category/{slug}/{target}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_messages:
    path : /messages
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_messages_send:
    path: /messages/send/{id}/{to}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_messages_list:
    path: /messages/list/{type}
    defaults: { _controller: UbidElectricityBundle:Default:public }

e_electricity_front_locale_messages_detail:
    path: /messages/detail/{id}
    defaults: { _controller: UbidElectricityBundle:Default:public }
