
ubid_electricity_dev:
    resource: "@UbidElectricityBundle/Controller/DefaultController.php"
    type:     annotation
    host: "ubid.com"
    prefix:   /

#ubid_electricity_test:
 #   resource: "@UbidElectricityBundle/Controller/DefaultController.php"
  #  type:     annotation
   # host: "ubid-electricity.continuousnet.com"
    #prefix:   /

#ubid_electricity_prod:
 #   resource: "@UbidElectricityBundle/Controller/DefaultController.php"
  #  type:     annotation
   # host: "admin.e-elctricity.com"
    #prefix:   /

thumb:
    resource: "@UbidElectricityBundle/Controller/ThumbController.php"
    type:     annotation
    prefix:   /

api_login_check:
    path: /api/login_check

api_login_check_lang:
    path: /{_locale}/api/login_check
    requirements:
        _locale: en|fr|ar

ubid_electricity_v1_api:
    resource: "@UbidElectricityBundle/Controller/ApiV1RESTController.php"
    type:   rest
    prefix:   /{_locale}/api/v1
    requirements:
        _locale: en|fr|ar

ubid_electricity_dashboard:
    resource: "@UbidElectricityBundle/Controller/DashboardRESTController.php"
    type:   rest
    prefix:   /{_locale}/api/dashboard
    requirements:
        _locale: en|fr|ar

ubid_electricity_alert_api:
    resource: "@UbidElectricityBundle/Controller/AlertRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_banner_api:
    resource: "@UbidElectricityBundle/Controller/BannerRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_banner_position_api:
    resource: "@UbidElectricityBundle/Controller/BannerPositionRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_banner_type_api:
    resource: "@UbidElectricityBundle/Controller/BannerTypeRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_bid_api:
    resource: "@UbidElectricityBundle/Controller/BidRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_bid_product_api:
    resource: "@UbidElectricityBundle/Controller/BidProductRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_bidding_type_api:
    resource: "@UbidElectricityBundle/Controller/BiddingTypeRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_buyer_api:
    resource: "@UbidElectricityBundle/Controller/BuyerRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_buyer_type_api:
    resource: "@UbidElectricityBundle/Controller/BuyerTypeRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_category_api:
    resource: "@UbidElectricityBundle/Controller/CategoryRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_click_api:
    resource: "@UbidElectricityBundle/Controller/ClickRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_country_api:
    resource: "@UbidElectricityBundle/Controller/CountryRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_group_api:
    resource: "@UbidElectricityBundle/Controller/GroupRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_hit_api:
    resource: "@UbidElectricityBundle/Controller/HitRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_impression_api:
    resource: "@UbidElectricityBundle/Controller/ImpressionRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_language_api:
    resource: "@UbidElectricityBundle/Controller/LanguageRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_log_api:
    resource: "@UbidElectricityBundle/Controller/LogRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_menu_api:
    resource: "@UbidElectricityBundle/Controller/MenuRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_menu_link_api:
    resource: "@UbidElectricityBundle/Controller/MenuLinkRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_message_api:
    resource: "@UbidElectricityBundle/Controller/MessageRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_notification_api:
    resource: "@UbidElectricityBundle/Controller/NotificationRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_post_api:
    resource: "@UbidElectricityBundle/Controller/PostRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_post_category_api:
    resource: "@UbidElectricityBundle/Controller/PostCategoryRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_post_type_api:
    resource: "@UbidElectricityBundle/Controller/PostTypeRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_product_type_api:
    resource: "@UbidElectricityBundle/Controller/ProductTypeRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_region_api:
    resource: "@UbidElectricityBundle/Controller/RegionRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_sector_api:
    resource: "@UbidElectricityBundle/Controller/SectorRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_supplier_api:
    resource: "@UbidElectricityBundle/Controller/SupplierRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_supplier_product_api:
    resource: "@UbidElectricityBundle/Controller/SupplierProductRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_supplier_type_api:
    resource: "@UbidElectricityBundle/Controller/SupplierTypeRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_tender_api:
    resource: "@UbidElectricityBundle/Controller/TenderRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_tender_product_api:
    resource: "@UbidElectricityBundle/Controller/TenderProductRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_tender_type_api:
    resource: "@UbidElectricityBundle/Controller/TenderTypeRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_translation_bidding_type_api:
    resource: "@UbidElectricityBundle/Controller/TranslationBiddingTypeRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_translation_buyer_type_api:
    resource: "@UbidElectricityBundle/Controller/TranslationBuyerTypeRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_translation_category_api:
    resource: "@UbidElectricityBundle/Controller/TranslationCategoryRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_translation_country_api:
    resource: "@UbidElectricityBundle/Controller/TranslationCountryRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_translation_menu_api:
    resource: "@UbidElectricityBundle/Controller/TranslationMenuRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_translation_menu_link_api:
    resource: "@UbidElectricityBundle/Controller/TranslationMenuLinkRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_translation_post_api:
    resource: "@UbidElectricityBundle/Controller/TranslationPostRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_translation_post_category_api:
    resource: "@UbidElectricityBundle/Controller/TranslationPostCategoryRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_translation_post_type_api:
    resource: "@UbidElectricityBundle/Controller/TranslationPostTypeRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_translation_product_type_api:
    resource: "@UbidElectricityBundle/Controller/TranslationProductTypeRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_translation_region_api:
    resource: "@UbidElectricityBundle/Controller/TranslationRegionRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_translation_sector_api:
    resource: "@UbidElectricityBundle/Controller/TranslationSectorRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_translation_supplier_type_api:
    resource: "@UbidElectricityBundle/Controller/TranslationSupplierTypeRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_translation_tender_type_api:
    resource: "@UbidElectricityBundle/Controller/TranslationTenderTypeRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_user_api:
    resource: "@UbidElectricityBundle/Controller/UserRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_user_setting_api:
    resource: "@UbidElectricityBundle/Controller/UserSettingRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_visit_api:
    resource: "@UbidElectricityBundle/Controller/VisitRESTController.php"
    type:   rest
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|ar
ubid_electricity_alert:
    resource: "@UbidElectricityBundle/Resources/config/routing/alert.yml"
    prefix:   /alert

ubid_electricity_banner:
    resource: "@UbidElectricityBundle/Resources/config/routing/banner.yml"
    prefix:   /banner

ubid_electricity_banner_position:
    resource: "@UbidElectricityBundle/Resources/config/routing/banner_position.yml"
    prefix:   /banner-position

ubid_electricity_banner_type:
    resource: "@UbidElectricityBundle/Resources/config/routing/banner_type.yml"
    prefix:   /banner-type

ubid_electricity_bid:
    resource: "@UbidElectricityBundle/Resources/config/routing/bid.yml"
    prefix:   /bid

ubid_electricity_bid_product:
    resource: "@UbidElectricityBundle/Resources/config/routing/bid_product.yml"
    prefix:   /bid-product

ubid_electricity_bidding_type:
    resource: "@UbidElectricityBundle/Resources/config/routing/bidding_type.yml"
    prefix:   /bidding-type

ubid_electricity_buyer:
    resource: "@UbidElectricityBundle/Resources/config/routing/buyer.yml"
    prefix:   /buyer

ubid_electricity_buyer_type:
    resource: "@UbidElectricityBundle/Resources/config/routing/buyer_type.yml"
    prefix:   /buyer-type

ubid_electricity_category:
    resource: "@UbidElectricityBundle/Resources/config/routing/category.yml"
    prefix:   /category

ubid_electricity_click:
    resource: "@UbidElectricityBundle/Resources/config/routing/click.yml"
    prefix:   /click

ubid_electricity_country:
    resource: "@UbidElectricityBundle/Resources/config/routing/country.yml"
    prefix:   /country

ubid_electricity_group:
    resource: "@UbidElectricityBundle/Resources/config/routing/group.yml"
    prefix:   /group

ubid_electricity_hit:
    resource: "@UbidElectricityBundle/Resources/config/routing/hit.yml"
    prefix:   /hit

ubid_electricity_impression:
    resource: "@UbidElectricityBundle/Resources/config/routing/impression.yml"
    prefix:   /impression

ubid_electricity_language:
    resource: "@UbidElectricityBundle/Resources/config/routing/language.yml"
    prefix:   /language

ubid_electricity_log:
    resource: "@UbidElectricityBundle/Resources/config/routing/log.yml"
    prefix:   /log

ubid_electricity_menu:
    resource: "@UbidElectricityBundle/Resources/config/routing/menu.yml"
    prefix:   /menu

ubid_electricity_menu_link:
    resource: "@UbidElectricityBundle/Resources/config/routing/menu_link.yml"
    prefix:   /menu-link

ubid_electricity_message:
    resource: "@UbidElectricityBundle/Resources/config/routing/message.yml"
    prefix:   /message

ubid_electricity_notification:
    resource: "@UbidElectricityBundle/Resources/config/routing/notification.yml"
    prefix:   /notification

ubid_electricity_post:
    resource: "@UbidElectricityBundle/Resources/config/routing/post.yml"
    prefix:   /post

ubid_electricity_post_category:
    resource: "@UbidElectricityBundle/Resources/config/routing/post_category.yml"
    prefix:   /post-category

ubid_electricity_post_type:
    resource: "@UbidElectricityBundle/Resources/config/routing/post_type.yml"
    prefix:   /post-type

ubid_electricity_product_type:
    resource: "@UbidElectricityBundle/Resources/config/routing/product_type.yml"
    prefix:   /product-type

ubid_electricity_region:
    resource: "@UbidElectricityBundle/Resources/config/routing/region.yml"
    prefix:   /region

ubid_electricity_sector:
    resource: "@UbidElectricityBundle/Resources/config/routing/sector.yml"
    prefix:   /sector

ubid_electricity_supplier:
    resource: "@UbidElectricityBundle/Resources/config/routing/supplier.yml"
    prefix:   /supplier

ubid_electricity_supplier_product:
    resource: "@UbidElectricityBundle/Resources/config/routing/supplier_product.yml"
    prefix:   /supplier-product

ubid_electricity_supplier_type:
    resource: "@UbidElectricityBundle/Resources/config/routing/supplier_type.yml"
    prefix:   /supplier-type

ubid_electricity_tender:
    resource: "@UbidElectricityBundle/Resources/config/routing/tender.yml"
    prefix:   /tender

ubid_electricity_tender_product:
    resource: "@UbidElectricityBundle/Resources/config/routing/tender_product.yml"
    prefix:   /tender-product

ubid_electricity_tender_type:
    resource: "@UbidElectricityBundle/Resources/config/routing/tender_type.yml"
    prefix:   /tender-type

ubid_electricity_translation_bidding_type:
    resource: "@UbidElectricityBundle/Resources/config/routing/translation_bidding_type.yml"
    prefix:   /translation-bidding-type

ubid_electricity_translation_buyer_type:
    resource: "@UbidElectricityBundle/Resources/config/routing/translation_buyer_type.yml"
    prefix:   /translation-buyer-type

ubid_electricity_translation_category:
    resource: "@UbidElectricityBundle/Resources/config/routing/translation_category.yml"
    prefix:   /translation-category

ubid_electricity_translation_country:
    resource: "@UbidElectricityBundle/Resources/config/routing/translation_country.yml"
    prefix:   /translation-country

ubid_electricity_translation_menu:
    resource: "@UbidElectricityBundle/Resources/config/routing/translation_menu.yml"
    prefix:   /translation-menu

ubid_electricity_translation_menu_link:
    resource: "@UbidElectricityBundle/Resources/config/routing/translation_menu_link.yml"
    prefix:   /translation-menu-link

ubid_electricity_translation_post:
    resource: "@UbidElectricityBundle/Resources/config/routing/translation_post.yml"
    prefix:   /translation-post

ubid_electricity_translation_post_category:
    resource: "@UbidElectricityBundle/Resources/config/routing/translation_post_category.yml"
    prefix:   /translation-post-category

ubid_electricity_translation_post_type:
    resource: "@UbidElectricityBundle/Resources/config/routing/translation_post_type.yml"
    prefix:   /translation-post-type

ubid_electricity_translation_product_type:
    resource: "@UbidElectricityBundle/Resources/config/routing/translation_product_type.yml"
    prefix:   /translation-product-type

ubid_electricity_translation_region:
    resource: "@UbidElectricityBundle/Resources/config/routing/translation_region.yml"
    prefix:   /translation-region

ubid_electricity_translation_sector:
    resource: "@UbidElectricityBundle/Resources/config/routing/translation_sector.yml"
    prefix:   /translation-sector

ubid_electricity_translation_supplier_type:
    resource: "@UbidElectricityBundle/Resources/config/routing/translation_supplier_type.yml"
    prefix:   /translation-supplier-type

ubid_electricity_translation_tender_type:
    resource: "@UbidElectricityBundle/Resources/config/routing/translation_tender_type.yml"
    prefix:   /translation-tender-type

ubid_electricity_user:
    resource: "@UbidElectricityBundle/Resources/config/routing/user.yml"
    prefix:   /user

ubid_electricity_user_setting:
    resource: "@UbidElectricityBundle/Resources/config/routing/user_setting.yml"
    prefix:   /user-setting

ubid_electricity_visit:
    resource: "@UbidElectricityBundle/Resources/config/routing/visit.yml"
    prefix:   /visit

public_ubid_electricity_dev:
    path:  /
    defaults: { _controller: UbidElectricityBundle:Default:public }
    host: "public.ubid.com"

public_ubid_electricity_test:
    path:  /
    defaults: { _controller: UbidElectricityBundle:Default:public }
    host: "e-elctricity.continuousnet.com"

public_ubid_electricity_prod:
    path:  /
    defaults: { _controller: UbidElectricityBundle:Default:public }
    host: "www.e-elctricity.com"

ubid_advanced_search:
    resource: "@UbidElectricityBundle/Controller/SearchRestController.php"
    type:   rest
    prefix: /api

ubid_upload_api:
    resource: "@UbidElectricityBundle/Controller/UploadRESTController.php"
    type:   rest
    prefix:   /upload
