
ubid_electricity:
    resource: "@UbidElectricityBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

thumb:
    resource: "@UbidElectricityBundle/Controller/ThumbController.php"
    type:     annotation
    prefix:   /

api_login_check:
    path: /api/login_check

api_login_check_lang:
    path: /{_locale}/api/login_check
    requirements:
        _locale: en|fr|ar

ubid_electricity_v1_api:
    resource: "@UbidElectricityBundle/Controller/ApiV1RESTController.php"
    type:   rest
    prefix:   /{_locale}/api/v1
    requirements:
        _locale: en|fr|ar

ubid_electricity_dashboard:
    resource: "@UbidElectricityBundle/Controller/DashboardRESTController.php"
    type:   rest
    prefix:   /{_locale}/api/dashboard
    requirements:
        _locale: en|fr|ar

